name: Example Workflow

on: 
  push:
    branches:
      - main  # This triggers the action on push to the main branch.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 21f3002214@ds.study.iitm.ac.in  # Your required step name containing the email
        run: echo "Hello, world!"  # Example command; replace with your own logic.
